FROM {{ item.image }}

ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get update --yes && \
    apt-get install sudo gnupg software-properties-common python3-pip --yes && \
    pip3 install --upgrade pip && \
    useradd -m -g sudo ansible && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/ansible